{{- if .Values.basicAuth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: dpn-nginx-basic-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
  .htpasswd: |
{{ .Values.basicAuth.htpasswd | indent 4 }}
{{- end }}
