apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sidecar.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.sidecar.serviceName }}
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sidecar-discovery
spec:
  type: ExternalName
  externalName: {{ .Values.sidecar.externalName }}
  ports:
    - name: grpc
      port: {{ .Values.sidecar.grpcPort }}
      targetPort: {{ .Values.sidecar.grpcPort }}
      protocol: TCP
    - name: http
      port: {{ .Values.sidecar.httpPort }}
      targetPort: {{ .Values.sidecar.httpPort }}
      protocol: TCP
