FROM curlimages/curl:8.6.0
USER root
COPY log-status-dashboard.ndjson    /dashboards/log-status-dashboard.ndjson
COPY otel-logs-index-template.json  /dashboards/otel-logs-index-template.json
COPY init-opensearch-dashboard.sh   /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["sh", "/init.sh"]
