apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Values.namespace | default "ns-dpn-health-01" }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl (.Files.Get "otel-collector-config.yaml") . | nindent 4 }}