apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "otel-collector.fullname" .) }}
  namespace: {{ .Values.namespace | default "ns-dpn-health-01" }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $name, $config := .Values.service.ports }}
  - name: {{ $name }}
    port: {{ $config.port }}
    targetPort: {{ $config.targetPort }}
    protocol: {{ $config.protocol }}
  {{- end }}
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}

# Made with Bob
